### ISSUE TITLE
Making use of md-icon directive of ngMaterial

### ISSUE THREAD

**Issue by dohomi** [nobitagit/ng-material-floating-button#12]
Hello,

Just found your really nice directive, looking awesome! Do you plan to allow the customization of the use of ```active|resting```icons? I would like to use the md-icon directive from the ngMaterial module with svg icons. Or can you point me how to adjust it? 

Thanks! Dominic

**Comment by nobitagit** [comment]
Hi there, that's a good question.
At the moment I guess the only way is to edit the template directly i guess, you should remove the `<i>` tags that contain the icon font and replace with your svg. I know it's far from ideal, but that's all I can think of atm.

It certainly would be interesting to provide a higher level of choice for the icon format out of the box, but it will only come with a refactor from the present code.

Thanks for the input, will mark this as enhancement and leave it open for now.

**Comment by robertbaker** [comment]
It would be great if you could have a version that uses material-angular directives (md-button) <md-icon md-svg-icon="pathtoicon or icon name"><md-icon>

**Comment by nobitagit** [comment]
@dohomi I tested some possible solutions for your request. 

You can already take a look at one in this [new branch](https://github.com/nobitagit/ng-material-floating-button/tree/ext).

My idea is still to provide font icon support out of the box as it is now, in order to keep the directive in sync with the original component.

At the same time though it would be nice to leave the ability to fully customise the icon formats or the html that stays inside each button. In this implementation you can pass your own template to the buttons. 
Here is an [example](http://embed.plnkr.co/6QryaAgziFIRkNySKRSy/preview) using SVGs instead of font icons, with template override. 

I have commented the [index source code](http://embed.plnkr.co/6QryaAgziFIRkNySKRSy/index.html) as a sort of readme for now. 

This is not yet merged in master, as i need more tests and also try other solutions but this for now seems to be doing its job. Let me know if you have the chance to test it.

**Comment by dohomi** [comment]
@nobitagit great news! Sounds to me like the best approach to customize the component for everybody. Thanks will check it out in my project and let you know if I bump into any issues.

**Comment by dohomi** [comment]
Hi,

here is a GIST where I documented all the steps I needed to do making your branch working with ngMaterial:

https://gist.github.com/dohomi/87f99590166ffddc1180

One confusing step was customizing ```button.tpl.html```and ```menu.tpl.html``` for matching the existing md-fab button style. This two files I had to copy/paste into the root of my project with keeping the same naming. Is it possible to adjust the ```templateUrl```that I can adjust the location of the files?

The look and feel is very nice, thanks working on this!

**Comment by sebastiengiroux** [comment]
+1

**Comment by nobitagit** [comment]
@dohomi thanks for the gist, will try to improve the branch and maybe ask again for your check.

**Comment by nobitagit** [comment]
v0.4 adds support for custom templates and also brings an optional default integration with Angular Material button and SVG icons with a dedicated template. 

Docs are still quite superficial about it but here's an [example](http://nobitagit.github.io/ng-material-floating-button/angular-material.html) using the provided template leveraging Angular Material's `md-button` and `md-icon`.

Still many improvements and test drives to be done, but seems to be working quite well for now, if anyone finds issues please report.

**Comment by robertbaker** [comment]
I actually went ahead with editing .3.

I wonder what the comparisons are:
https://gist.github.com/robertbaker/cd75044253294d0b4dde
