### ISSUE TITLE
Having 2 repo's is a bit confusing

### ISSUE THREAD

**Issue by robertbaker** [nobitagit/ng-material-floating-button#32]

**Comment by nobitagit** [comment]
There is a reason behind the fact that there is an upstream repo for the layout/styles and i always try to pull the changes from there rather than push framework-specific changes from downstream.

My idea is to provide a minimal vanilla component ([Mfb](https://github.com/nobitagit/material-floating-button)) that is totally free from dependencies (no jQuery, no Angular, no React, just html, CSS and - optionally - vanilla Js), that is as flexible as possible. The goal is to have a basic component that can be either used as is or easily wrapped for present and future frameworks, as in fact is being used right now with this Angular wrapper or with the React version.

As I think of it, if I have trouble adapting the core component to a framework version, then it means that the core is not as flexible as it should. That's why i think that all style changes has to be applied and tested there.

I know it may seem a bit more trouble but I guess that in the end it just makes for a stronger and more flexible base component that can be tested in many different situations and implementations.
