### ISSUE TITLE
Directive does not work for more than 4 buttons

### ISSUE THREAD

**Issue by bdteo** [nobitagit/ng-material-floating-button#48]
As I found it is the way css is used that limits the number of buttons that could be used.
Using nth-child this way really seems to be very weird, WET and fragile way to achieve what this directive does.
A better and more robust approach could be using ngAnimate staggering animations and calculating offset in directive itself (using JS).
 
PS
I didnt actually intend showing more than 4 buttons simultaneously but hiding buttons does not help (using ng-show, ng-hide) and using ng-if is not an option since it triggers some weird animation.

**Comment by bdteo** [comment]
Sadly, this repo seems to be both of low quality and abandoned.

**Comment by nobitagit** [comment]
Hi there thanks for the (let's face it, not so) kind words, but I am sincerely happy to answer.

To get the issue out of the way I suggest two basic things:

- read the docs ([here](https://github.com/nobitagit/ng-material-floating-button#more-customisations) and [here](https://github.com/nobitagit/ng-material-floating-button/tree/master/mfb#scsscss))
- look for other identical, previously closed issues ([here](https://github.com/nobitagit/ng-material-floating-button/issues/29) and [here](https://github.com/nobitagit/ng-material-floating-button/issues/28#issuecomment-96980288))

This should help you find a solution for this very issue and also future ones on Github.

Now let's talk about the code.

I opted for relying on scss (not just CSS, as you seem to think, and there's quite a difference as you'll see) rather than just js for supporting *n* buttons for a series of reason, most notably:

- I care about performances and whenever I have a choice between implementing something in CSS and in Js I opt for the first.  Surprisingly it looks like I'm not the only one.

- most of the time a menu has a fixed number or at least a very predictable range of items. Dynamic calculation is in 99% of the times **not** required and a wasteful overhead, simple as that.

- it's actually quite easy to add and support a new button. You type **one** number, recompile your scss and you're done. The relevant code is calculated and generated for you by the loops you see in the scss. Is that DRY enough? 

- if you have some sort of dynamic number (let's say that your menu items span from 4 to 6 according to different scenarios) it seems reasonable to me to add 10 lines of (automatically generated) CSS and support a 6th button that may or may not display, rather than recalculate the styles each time via js, quite surely losing the performance benefits of a CSS approach.

That being said, I know the choices we make while coding are very likely to be tradeoffs rather than universal solutions, and this tool makes no exception. 

And after all, hey, we're on Github, you are free (and encouraged) to contribute on other projects to make them better, fork them if you think you can go on with a better version on your own or even create one from scratch if the right tool is just not there in your opinion.

I hope not to sound patronising as that's really not my intent. The tone of my reply is in part due to the fact that unfortunately (but not so surprisingly) you have no public repo for me to infer that you've already been through this before on your own. I encourage you to share on Github an implementation of a similar component or contribute to any kind other open source projects, if not to see how many challenges you face when trying to provide a solution that covers many different use cases that go beyond what you need in a single specific project (and we're talking about a very simple menu here).

Cheers, I am closing this issue because as said the question is a duplicate and has already been closed previously.

**Comment by bdteo** [comment]
Sorry if what I wrote was too harsh and made you feel bad. I actually liked very much the look, feel and the smoothness of your implementation when it comes to practical use and I am sure that relying mostly on css helped a lot. Maybe your approach is very good for most cases but it is still verbose when it comes to what I need. If it was only this (but not other flaws that concerned me when I indeed read your code) it wouldn't actually had stopped me from using your implementation.

Calculating position using js was really just a suggestion and using static positioning might just be enough being concerned with performance. "Premature optimization is the root of all evil" however, you know.

You are right and I am sure that there are many challenges to consider when it comes to covering many use cases. I ended up writing my own implementation that fits better my case. There is only one place where I will use it though. So, at this moment it does not worth spending more time to make my implementation good enough to share. I would, however, gladly contribute in the future when I have something polished enough to be shared.

If you haven't seen it, you could check angular-material speed dial implementation. It doesn't seem to be very polished but some good ideas might come to you.

Thanks for your answer and sorry again for the harsh words. Cheers!
