### ISSUE TITLE
Smaller child action buttons

### ISSUE THREAD

**Issue by ivamluz** [nobitagit/ng-material-floating-button#5]
Is it possible to have smaller child action buttons, just like Google's Inbox?

I've tried to change buttons height and width, but I'm facing a hard time to adjust the spacing between the buttons after that:

![selection_046](https://cloud.githubusercontent.com/assets/1983873/6127174/4f75e36a-b10f-11e4-88ff-494adce14288.jpg)

Could you please provide any advice on this?

**Comment by nobitagit** [comment]
Yes, this should be possible but there's an issue in the original component, as you show.

There's a pull request going on [here](https://github.com/nobitagit/material-floating-button/pull/4) waiting for approval about this. I haven't had the time yet to review/merge it, so I can't tell for sure if it does solve the issue but it definitely addresses it in some way.

If you are in a hurry you can see if that's a solution. Otherwise in the next few days I will take a look into it anyway, review that PR in the original component and then pull the changes in the Angular version too.

**Comment by nobitagit** [comment]
PR has been merged and pulled from upstream, this issue should be solved.
